# 過剰決定系（優決定系）

In [8]:
import numpy as np
A=np.matrix([[2,1],[3,1],[7,1]])
a2 = A.T*A
B=np.matrix([[3],[6],[5]])

X = np.linalg.inv(A.T*A)*A.T*B
X

matrix([[0.21428571],
        [3.80952381]])

# 不足決定系（劣決定系）

In [9]:
import numpy as np
A=np.matrix([[2,1]])
a2 = A.T*A
B=np.matrix([[3]])

X = np.linalg.inv(A.T*A)*A.T*B
X

LinAlgError: Singular matrix

In [2]:
t=np.array([[2,1],[3,1]])
s=np.array([[2,1],[3,1]])
t*s


array([[4, 1],
       [9, 1]])

In [19]:
import numpy as np
A=np.matrix([[1,2]])
print(A.T)
a2 = A*A.T
print(a2)
f=np.linalg.matrix_rank(A)
print(f)
B=np.matrix([[3]])

X = np.linalg.inv(A*A.T)
X

[[1]
 [2]]
[[5]]
1


matrix([[0.2]])